"use client";

import { useConvexQuery, convexApi } from "../hooks/useConvexSafe";

// Sample data — used as fallback when Convex isn't connected
interface Metric {
  label: string;
  current: number;
  target: number;
  color: string;
}

const SAMPLE_METRICS: Metric[] = [
  { label: "Content", current: 2, target: 2, color: "var(--color-op-green)" },
  { label: "Experiments", current: 1, target: 1, color: "var(--color-op-blue)" },
  { label: "Feedback", current: 3, target: 3, color: "var(--color-op-amber)" },
  { label: "Community", current: 12, target: 50, color: "var(--color-op-green)" },
];

const SAMPLE_WEEK = 1;

function MetricBar({ metric }: { metric: Metric }) {
  const pct = Math.min((metric.current / metric.target) * 100, 100);
  const isComplete = metric.current >= metric.target;

  return (
    <div className="space-y-2">
      <div className="flex items-baseline justify-between">
        <span className="text-sm text-[var(--color-op-text)]">
          {metric.label}
        </span>
        <span className="text-sm font-mono">
          <span
            className={
              isComplete
                ? "text-[var(--color-op-green)]"
                : "text-[var(--color-op-text)]"
            }
          >
            {metric.current}
          </span>
          <span className="text-[var(--color-op-dim)]">
            /{metric.target}
          </span>
        </span>
      </div>
      <div className="w-full h-2.5 rounded-full bg-[var(--color-op-card-alt)]">
        <div
          className="h-full rounded-full transition-all duration-500"
          style={{ width: `${pct}%`, backgroundColor: metric.color }}
        />
      </div>
    </div>
  );
}

export default function ReportPage() {
  // CONVEX: wire to api.weeklyReports.getLatest when connected
  const convexReport = useConvexQuery(convexApi?.weeklyReports?.getLatest, {});

  // Build metrics from Convex report, or fall back to sample data
  const weekNumber = convexReport
    ? (convexReport as any).weekNumber
    : SAMPLE_WEEK;

  const metrics: Metric[] = convexReport
    ? [
        {
          label: "Content",
          current: (convexReport as any).contentCount ?? 0,
          target: 2,
          color: "var(--color-op-green)",
        },
        {
          label: "Experiments",
          current: (convexReport as any).experimentCount ?? 0,
          target: 1,
          color: "var(--color-op-blue)",
        },
        {
          label: "Feedback",
          current: (convexReport as any).feedbackCount ?? 0,
          target: 3,
          color: "var(--color-op-amber)",
        },
        {
          label: "Community",
          current: (convexReport as any).interactionCount ?? 0,
          target: 50,
          color: "var(--color-op-green)",
        },
      ]
    : SAMPLE_METRICS;

  const handlePreview = () => {
    // Will open preview modal or navigate to preview page
    alert("Preview report — not yet implemented");
  };

  const handleSendToSlack = () => {
    // Will call Convex mutation to send to Slack
    alert("Send to Slack — not yet implemented");
  };

  const handleExportMD = () => {
    // Use Convex report content if available, else generate from metrics
    const reportContent = convexReport
      ? (convexReport as any).reportContent
      : null;

    const md = reportContent ?? [
      `# Week ${weekNumber} Report`,
      "",
      "## Metrics",
      ...metrics.map(
        (m) => `- **${m.label}**: ${m.current}/${m.target}`
      ),
      "",
      "---",
      `Generated by GrowthCat Operator`,
    ].join("\n");

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `growthcat-week-${weekNumber}-report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const allComplete = metrics.every((m) => m.current >= m.target);

  return (
    <div className="space-y-6 max-w-3xl">
      <div className="flex items-baseline justify-between">
        <h1 className="text-xl font-semibold text-[var(--color-op-text)]">
          Week {weekNumber} Report
        </h1>
        {allComplete ? (
          <span className="flex items-center gap-1.5 text-sm text-[var(--color-op-green)]">
            <span className="inline-block w-2 h-2 rounded-full bg-[var(--color-op-green)]" />
            All targets met
          </span>
        ) : (
          <span className="text-sm text-[var(--color-op-muted)]">
            In progress
          </span>
        )}
      </div>

      {/* Metric progress bars */}
      <div className="rounded-lg bg-[var(--color-op-card)] border border-[var(--color-op-border)] p-5 space-y-5">
        {metrics.map((metric) => (
          <MetricBar key={metric.label} metric={metric} />
        ))}
      </div>

      {/* Summary */}
      <div className="rounded-lg bg-[var(--color-op-card)] border border-[var(--color-op-border)] p-5">
        <h2 className="text-xs font-medium text-[var(--color-op-dim)] uppercase tracking-wider mb-3">
          Summary
        </h2>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          {metrics.map((m) => (
            <div key={m.label} className="text-center">
              <div
                className="text-2xl font-bold"
                style={{
                  color:
                    m.current >= m.target
                      ? "var(--color-op-green)"
                      : "var(--color-op-text)",
                }}
              >
                {Math.round((m.current / m.target) * 100)}%
              </div>
              <div className="text-xs text-[var(--color-op-muted)] mt-0.5">
                {m.label}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-3">
        <button
          onClick={handlePreview}
          className="px-4 py-2 rounded-lg text-sm font-medium bg-[var(--color-op-card)] border border-[var(--color-op-border)] text-[var(--color-op-text)] hover:bg-[var(--color-op-card-alt)] transition-colors"
        >
          Preview Report
        </button>
        <button
          onClick={handleSendToSlack}
          className="px-4 py-2 rounded-lg text-sm font-medium bg-[var(--color-op-card)] border border-[var(--color-op-border)] text-[var(--color-op-text)] hover:bg-[var(--color-op-card-alt)] transition-colors"
        >
          Send to Slack
        </button>
        <button
          onClick={handleExportMD}
          className="px-4 py-2 rounded-lg text-sm font-medium bg-[var(--color-op-green)] text-white hover:opacity-90 transition-opacity"
        >
          Export MD
        </button>
      </div>
    </div>
  );
}
