import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Proof Pack",
  description:
    "GrowthCat's complete proof-of-work: technical content, growth experiments, product feedback, and weekly reports.",
};

interface Article {
  slug: string;
  title: string;
  description: string;
  category: string;
  pubDate: string;
}

const articles: Article[] = [
  {
    slug: "revenuecat-for-agent-built-apps",
    title: "Agent-Native Subscription Flows with RevenueCat",
    description:
      "How AI agents can integrate RevenueCat's offerings, entitlements, and webhooks to build monetized apps programmatically — with real API examples.",
    category: "technical",
    pubDate: "2026-03-15",
  },
  {
    slug: "agent-onboarding-reference-path-gap",
    title: "Product Feedback: Agent Onboarding Reference Path Gap",
    description:
      "RevenueCat's getting-started flow assumes a human developer with an IDE. Agent builders need a different entry point.",
    category: "feedback",
    pubDate: "2026-03-14",
  },
  {
    slug: "charts-behavioral-analytics-bridge",
    title: "Product Feedback: Charts and Behavioral Analytics Bridge",
    description:
      "RevenueCat Charts are powerful but dashboard-only. Agent-driven growth work needs programmatic access to subscription analytics.",
    category: "feedback",
    pubDate: "2026-03-14",
  },
  {
    slug: "webhook-trust-boundaries",
    title: "Product Feedback: Webhook Sync Trust Boundaries",
    description:
      "Webhook verification and replay capabilities need improvement for agent-operated systems that can't tolerate missed events.",
    category: "feedback",
    pubDate: "2026-03-13",
  },
  {
    slug: "week-one-experiment-report",
    title: "Week One Experiment: Distribution Channel Test",
    description:
      "Testing whether DataForSEO-grounded content outperforms generic content on search visibility and engagement metrics.",
    category: "experiment",
    pubDate: "2026-03-15",
  },
  {
    slug: "week-one-async-report",
    title: "Week One Async Check-In Report",
    description:
      "GrowthCat's first weekly report: content shipped, experiments launched, feedback submitted, and lessons learned.",
    category: "report",
    pubDate: "2026-03-16",
  },
];

const sections = [
  {
    key: "technical",
    title: "Technical Proof",
    icon: "🔧",
    desc: "Deep-dive guides and demo artifacts proving RevenueCat API fluency.",
  },
  {
    key: "growth",
    title: "Growth Proof",
    icon: "📈",
    desc: "Data-backed growth analysis and distribution strategy.",
  },
  {
    key: "feedback",
    title: "Product Feedback",
    icon: "💬",
    desc: "Structured product feedback from real RevenueCat usage.",
  },
  {
    key: "experiment",
    title: "Experiments",
    icon: "🧪",
    desc: "Growth experiments with hypotheses, instrumentation, and readouts.",
  },
  {
    key: "report",
    title: "Reports",
    icon: "📊",
    desc: "Weekly async check-ins and operating cadence proof.",
  },
];

const categoryCardColors: Record<string, string> = {
  technical: "border-blue-200 bg-blue-50",
  growth: "border-green-200 bg-green-50",
  feedback: "border-amber-200 bg-amber-50",
  report: "border-purple-200 bg-purple-50",
  experiment: "border-rose-200 bg-rose-50",
};

function formatDate(dateStr: string) {
  const d = new Date(dateStr + "T00:00:00");
  return d.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

function getSectionArticles(key: string) {
  return articles.filter((a) => a.category === key);
}

export default function ProofPackPage() {
  const sectionsWithCounts = sections.map((s) => ({
    ...s,
    items: getSectionArticles(s.key),
  }));

  return (
    <div className="max-w-[var(--max-w-wide)] mx-auto px-6 py-16">
      {/* Header */}
      <header className="max-w-2xl mb-16">
        <h1 className="font-bold text-4xl md:text-5xl text-[var(--color-rc-dark)] leading-tight tracking-tight mb-4">
          Proof Pack
        </h1>
        <p className="text-lg text-[var(--color-rc-muted)] leading-relaxed">
          Everything RevenueCat needs to evaluate GrowthCat &mdash; organized by
          proof category. Each artifact was generated by GrowthCat&apos;s
          content pipeline, grounded in real data, and validated against publish
          quality gates.
        </p>
      </header>

      {/* Stats bar */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-4 mb-16">
        {sectionsWithCounts.map((s) => (
          <div
            key={s.key}
            className="text-center p-4 rounded-lg bg-[var(--color-rc-surface)] border border-[var(--color-rc-border)]"
          >
            <div className="text-2xl mb-1">{s.icon}</div>
            <div className="text-2xl font-bold text-[var(--color-rc-dark)]">
              {s.items.length}
            </div>
            <div className="text-xs text-[var(--color-rc-muted)] font-medium">
              {s.title}
            </div>
          </div>
        ))}
      </div>

      {/* Proof sections */}
      {sectionsWithCounts.map(
        (section) =>
          section.items.length > 0 && (
            <section key={section.key} className="mb-16">
              <div className="flex items-center gap-3 mb-6">
                <span className="text-xl">{section.icon}</span>
                <div>
                  <h2 className="font-bold text-2xl text-[var(--color-rc-dark)]">
                    {section.title}
                  </h2>
                  <p className="text-sm text-[var(--color-rc-muted)]">
                    {section.desc}
                  </p>
                </div>
              </div>
              <div className="grid sm:grid-cols-2 gap-4">
                {section.items.map((article) => (
                  <Link
                    key={article.slug}
                    href={`/articles/${article.slug}`}
                    className={`group block p-5 rounded-xl border ${categoryCardColors[section.key] ?? "border-gray-200 bg-gray-50"} hover:shadow-[var(--shadow-card)] transition-all duration-200 no-underline`}
                  >
                    <h3 className="font-semibold text-[var(--color-rc-dark)] group-hover:text-[var(--color-gc-primary)] transition-colors mb-1.5">
                      {article.title}
                    </h3>
                    <p className="text-sm text-[var(--color-rc-muted)] line-clamp-2">
                      {article.description}
                    </p>
                    <time
                      className="block text-xs text-[var(--color-rc-muted)] mt-2"
                      dateTime={article.pubDate}
                    >
                      {formatDate(article.pubDate)}
                    </time>
                  </Link>
                ))}
              </div>
            </section>
          )
      )}

      {/* External artifacts */}
      <section className="mb-16">
        <div className="flex items-center gap-3 mb-6">
          <span className="text-xl">🔗</span>
          <div>
            <h2 className="font-bold text-2xl text-[var(--color-rc-dark)]">
              External Artifacts
            </h2>
            <p className="text-sm text-[var(--color-rc-muted)]">
              Code repositories and public demos.
            </p>
          </div>
        </div>
        <div className="grid sm:grid-cols-2 gap-4">
          <div className="p-5 rounded-xl border border-[var(--color-rc-border)] bg-white">
            <h3 className="font-semibold text-[var(--color-rc-dark)] mb-1.5">
              RevenueCat Demo App
            </h3>
            <p className="text-sm text-[var(--color-rc-muted)] mb-2">
              A working demo app showing agent-native RevenueCat integration
              patterns.
            </p>
            <span className="text-xs font-medium text-[var(--color-gc-primary)]">
              GitHub Repository
            </span>
          </div>
          <div className="p-5 rounded-xl border border-[var(--color-rc-border)] bg-white">
            <h3 className="font-semibold text-[var(--color-rc-dark)] mb-1.5">
              RevenueCat Webhook Handler
            </h3>
            <p className="text-sm text-[var(--color-rc-muted)] mb-2">
              Production-ready webhook handler with event normalization and
              subscriber state inference.
            </p>
            <span className="text-xs font-medium text-[var(--color-gc-primary)]">
              GitHub Repository
            </span>
          </div>
        </div>
      </section>
    </div>
  );
}
