import { query, mutation, internalMutation } from "./_generated/server";
import { v } from "convex/values";

export const getLatest = query({
  args: {},
  handler: async (ctx) => {
    return await ctx.db
      .query("weeklyReports")
      .withIndex("by_week")
      .order("desc")
      .first();
  },
});

export const getByWeek = query({
  args: { weekNumber: v.number() },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("weeklyReports")
      .withIndex("by_week", (q) => q.eq("weekNumber", args.weekNumber))
      .first();
  },
});

export const save = mutation({
  args: {
    weekNumber: v.number(),
    contentCount: v.number(),
    experimentCount: v.number(),
    feedbackCount: v.number(),
    interactionCount: v.number(),
    reportContent: v.string(),
    slackTs: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // Check if a report for this week already exists
    const existing = await ctx.db
      .query("weeklyReports")
      .withIndex("by_week", (q) => q.eq("weekNumber", args.weekNumber))
      .first();

    if (existing) {
      await ctx.db.patch(existing._id, args);
      return existing._id;
    }

    return await ctx.db.insert("weeklyReports", args);
  },
});

// Internal mutation triggered by the weekly report cron job
export const generateReport = internalMutation({
  args: {},
  handler: async (ctx) => {
    console.log("[cron] generateReport: starting weekly report generation");

    // Count artifacts created this week
    const now = Date.now();
    const oneWeekAgo = now - 7 * 24 * 60 * 60 * 1000;

    const recentArtifacts = await ctx.db
      .query("artifacts")
      .order("desc")
      .collect();
    const contentCount = recentArtifacts.filter(
      (a) => a._creationTime > oneWeekAgo
    ).length;

    const recentExperiments = await ctx.db
      .query("experiments")
      .order("desc")
      .collect();
    const experimentCount = recentExperiments.filter(
      (e) => e._creationTime > oneWeekAgo
    ).length;

    const recentFeedback = await ctx.db
      .query("feedbackItems")
      .order("desc")
      .collect();
    const feedbackCount = recentFeedback.filter(
      (f) => f._creationTime > oneWeekAgo
    ).length;

    const recentInteractions = await ctx.db
      .query("communityInteractions")
      .order("desc")
      .collect();
    const interactionCount = recentInteractions.filter(
      (i) => i._creationTime > oneWeekAgo
    ).length;

    // Calculate ISO week number
    const date = new Date(now);
    const startOfYear = new Date(date.getFullYear(), 0, 1);
    const days = Math.floor(
      (date.getTime() - startOfYear.getTime()) / (24 * 60 * 60 * 1000)
    );
    const weekNumber = Math.ceil((days + startOfYear.getDay() + 1) / 7);

    const reportContent = [
      `# Weekly Report - Week ${weekNumber}`,
      ``,
      `## Summary`,
      `- Content pieces: ${contentCount}`,
      `- Experiments: ${experimentCount}`,
      `- Feedback items: ${feedbackCount}`,
      `- Community interactions: ${interactionCount}`,
      ``,
      `_Auto-generated by GrowthRat cron. Replace with LLM-generated summary._`,
    ].join("\n");

    await ctx.db.insert("weeklyReports", {
      weekNumber,
      contentCount,
      experimentCount,
      feedbackCount,
      interactionCount,
      reportContent,
    });

    console.log(
      `[cron] generateReport: saved week ${weekNumber} report (content=${contentCount}, experiments=${experimentCount}, feedback=${feedbackCount}, interactions=${interactionCount})`
    );
  },
});
