/**
 * GrowthCat Agent Network
 *
 * Multi-agent system using Inngest AgentKit with deterministic routing.
 * 5 agents: planner → content → growth → feedback → community
 *
 * The router inspects shared state to determine which agent runs next,
 * following a weekly plan generated by the planner agent.
 */

import { anthropic, createAgent, createNetwork } from "@inngest/agent-kit";
import { weeklyPlanner } from "./planner";
import { contentAgent } from "./content";
import { growthAgent } from "./growth";
import { feedbackAgent } from "./feedback";
import { communityAgent } from "./community";

export const growthCatNetwork = createNetwork({
  name: "growthcat",
  agents: [weeklyPlanner, contentAgent, growthAgent, feedbackAgent, communityAgent],
  defaultModel: anthropic({
    model: "claude-sonnet-4-20250514",
    defaultParameters: { max_tokens: 4096 },
  }),
} as Parameters<typeof createNetwork>[0]);
